{{- $name := include "karmada.name" . -}}
{{- $systemNamespace := .Values.systemNamespace -}}
{{- if and (or (eq .Values.installMode "component") (eq .Values.installMode "host")) (has "descheduler" .Values.components) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-descheduler
  namespace: {{ include "karmada.namespace" . }}
  labels:
  {{- include "karmada.descheduler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.descheduler.replicaCount }}
  selector:
    matchLabels:
      {{- include "karmada.descheduler.labels" . | nindent 6 }}
  {{- with .Values.descheduler.strategy }}
  strategy:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.descheduler.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "karmada.descheduler.labels" . | nindent 8 }}
        {{- include "karmada.descheduler.podLabels" . | nindent 8 }}
    spec:
      {{- include "karmada.descheduler.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.descheduler.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.descheduler.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.descheduler.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: false
      initContainers:
        {{- include "karmada.initContainer.waitStaticResource" . | nindent 8 }}
      containers:
        - name: {{ $name }}-descheduler
          image: {{ template "karmada.descheduler.image" . }}
          imagePullPolicy: {{ .Values.descheduler.image.pullPolicy }}
          env:
            {{- include "karmada.env.podIP" . | nindent 12 }}
          command:
            - /bin/karmada-descheduler
            - --kubeconfig=/etc/kubeconfig
            - --metrics-bind-address=$(POD_IP):8080
            - --health-probe-bind-address=$(POD_IP):10358
            - --leader-elect-resource-namespace={{ $systemNamespace }}
            - --scheduler-estimator-ca-file=/etc/karmada/pki/server-ca.crt
            - --scheduler-estimator-cert-file=/etc/karmada/pki/karmada.crt
            - --scheduler-estimator-key-file=/etc/karmada/pki/karmada.key
            - --v=4
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10358
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          volumeMounts:
            - name: karmada-certs
              mountPath: /etc/karmada/pki
              readOnly: true
          {{- include "karmada.kubeconfig.volumeMount" . | nindent 12 }}
          resources:
          {{- toYaml .Values.descheduler.resources | nindent 12 }}
      priorityClassName: {{ .Values.descheduler.priorityClassName }}
      volumes:
      {{- include "karmada.descheduler.kubeconfig.volume" . | nindent 8 }}
      {{- include "karmada.scheduler.cert.volume" . | nindent 8 }}

{{ if .Values.descheduler.podDisruptionBudget }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}-descheduler
  namespace: {{ include "karmada.namespace" . }}
  labels:
    {{- include "karmada.descheduler.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "karmada.descheduler.labels" . | nindent 6}}
  {{ toYaml .Values.descheduler.podDisruptionBudget | nindent 2 }}
{{- end -}}

{{- end }}
