name: CLI
on:
  # Run this workflow every time a new commit pushed to upstream/fork repository.
  # Run workflow on fork repository will help contributors find and resolve issues before sending a PR.
  push:
    # Exclude branches created by Dependabot to avoid triggering current workflow
    # for PRs initiated by Dependabot.
    branches-ignore:
      - 'dependabot/**'
  pull_request:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
permissions:
  contents: read  # Required to check out the code
jobs:
  test-on-kubernetes-matrix:
    name: Test on Kubernetes
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # Here support the latest three minor releases of Kubernetes, this can be considered to be roughly
        # the same as the End of Life of the Kubernetes release: https://kubernetes.io/releases/
        # Please remember to update the CI Schedule Workflow when we add a new version.
        k8s: [ v1.32.0, v1.33.0, v1.34.0 ]
    steps:
      # Free up disk space on Ubuntu
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed, if set to "true" but frees about 6 GB
          tool-cache: false
          # all of these default to true, but feel free to set to "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: false
      - name: checkout code
        uses: actions/checkout@v6
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          # We need to guess version via git tags.
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: setup init e2e test environment
        run: |
          export CLUSTER_VERSION=kindest/node:${{ matrix.k8s }}
          hack/init-e2e-environment.sh
      - name: run e2e
        run: |
          export ARTIFACTS_PATH=${{ github.workspace }}/karmada-init-e2e-logs/${{ matrix.k8s }}/
          export REGISTRY="docker.io/karmada"
          export VERSION="latest"
          hack/run-e2e-init.sh
      - name: upload logs
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: karmada_init_e2e_log_${{ matrix.k8s }}
          path: ${{ github.workspace }}/karmada-init-e2e-logs/${{ matrix.k8s }}/
      - name: upload kind logs
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: karmada_init_kind_log_${{ matrix.k8s }}
          path: /tmp/karmada/

  init-config:
    name: init with config file
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # Latest three minor releases of Kubernetes
        k8s: [ v1.32.0, v1.33.0, v1.34.0 ]
    steps:
      - name: checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: run karmadactl init with config file test
        run: |
          export CLUSTER_VERSION=kindest/node:${{ matrix.k8s }}
          
          # Run custom test for workload configuration deployment
          hack/cli-testing-init-with-config.sh
          
          # run a single e2e
          export PULL_BASED_CLUSTERS="config-member1:${HOME}/.kube/config-member1.config"
          export KUBECONFIG=${HOME}/.kube/karmada-host.config:${HOME}/karmada/karmada-apiserver.config
          GO111MODULE=on go install github.com/onsi/ginkgo/v2/ginkgo
          ginkgo -v --race --trace -p  --focus="[BasicPropagation] propagation testing deployment propagation testing"  ./test/e2e/suites/base
      - name: export logs for config test
        if: always()
        run: |
          export ARTIFACTS_PATH=${{ github.workspace }}/karmadactl-test-logs/${{ matrix.k8s }}/config
          mkdir -p $ARTIFACTS_PATH
          
          mkdir -p $ARTIFACTS_PATH/karmada-host
          kind export logs --name=karmada-host $ARTIFACTS_PATH/karmada-host
      - name: upload config test logs
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: karmadactl_config_test_logs_${{ matrix.k8s }}
          path: ${{ github.workspace }}/karmadactl-test-logs/${{ matrix.k8s }}/config/

  test-on-kubernetes-split-secret:
    name: Test on Kubernetes (Split Secret)
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # Latest three minor releases of Kubernetes
        k8s: [ v1.31.0, v1.32.0, v1.33.0 ]
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: run karmadactl init test (split secret layout)
        run: |
          export CLUSTER_VERSION=kindest/node:${{ matrix.k8s }}

          # init e2e environment with split secret layout
          hack/cli-testing-environment-split-secret.sh

          # run a single e2e
          export PULL_BASED_CLUSTERS="split-secret-member1:${HOME}/.kube/split-secret-member1.config"  
          export KUBECONFIG=${HOME}/.kube/karmada-host.config:${HOME}/karmada/karmada-apiserver.config
          GO111MODULE=on go install github.com/onsi/ginkgo/v2/ginkgo
          ginkgo -v --race --trace -p  --focus="[BasicPropagation] propagation testing deployment propagation testing"  ./test/e2e/suites/base
      - name: export logs (split secret)
        if: always()
        run: |
          export ARTIFACTS_PATH=${{ github.workspace }}/karmadactl-test-logs/${{ matrix.k8s }}/split-secret
          mkdir -p $ARTIFACTS_PATH

          mkdir -p $ARTIFACTS_PATH/karmada-host
          kind export logs --name=karmada-host $ARTIFACTS_PATH/karmada-host
      - name: upload logs (split secret)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karmadactl_split_secret_test_logs_${{ matrix.k8s }}
          path: ${{ github.workspace }}/karmadactl-test-logs/${{ matrix.k8s }}/split-secret/
